import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <div className="bg-neutral-400 flex items-center justify-center h-24 text-3xl font-sans font-semibold tracking-wide">
            Test JWT Auth
          </div>
          <div className="bg-neutral-500">
            <div className='hover:bg-neutral-400 px-2 my-1 rounded-md block float-left'>
              <Link href='/' className='font-medium text-sm text-neutral-800'>Home</Link>
            </div>
            <div className='hover:bg-neutral-400 px-2 my-1 rounded-md block float-left'>
              <Link  href='#' className='font-medium text-sm text-neutral-800'>Test 2</Link >
            </div>
            <div className='hover:bg-neutral-400 px-2 my-1 rounded-md block float-right'>
              <Link  href='/login/' className='font-medium text-sm text-neutral-800 '>Login</Link >
            </div>
          </div>
          <div className="flex grow">
            <div className="bg-neutral-950 min-w-[200px]">Sidebar</div>
            <div className="bg-neutral-200 grow py-1 px-2">
              {children}
            </div>
          </div>
          <div className="bg-neutral-500">
            Footer
          </div>
        </div>
        </body>
    </html>
  )
}
